# Generated by Django 5.1.5 on 2025-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Section Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/about/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Activity Title')),
                ('description', models.TextField(verbose_name='Activity Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/activities/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/blog/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/events/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('announcement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Announcement Text')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Main Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('background_image', models.ImageField(upload_to='uploads/hero/', verbose_name='Background Image')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Link Name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sermon Title')),
                ('speaker', models.CharField(max_length=255, verbose_name='Speaker Name')),
                ('date', models.DateTimeField(verbose_name='Sermon Date')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/sermons/', verbose_name='Audio File')),
                ('description', models.TextField(verbose_name='Sermon Description')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('role', models.CharField(max_length=255, verbose_name='Role/Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/team/', verbose_name='Profile Image')),
                ('bio', models.TextField(verbose_name='Short Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Person's Name")),
                ('feedback', models.TextField(verbose_name='Testimonial / Feedback')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials/', verbose_name='Image (Optional)')),
            ],
        ),
    ]
