# Generated by Django 5.1.5 on 2025-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+0123456789', help_text='Enter phone number in international format (+XXX...)', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(default='info@example.com', max_length=254, verbose_name='Email Address')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('signup_url', models.URLField(default='/auth/login', verbose_name='Signup/Login URL')),
            ],
            options={
                'verbose_name': 'Header Settings',
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
