# Generated by Django 5.1.5 on 2025-03-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='signup_url',
        ),
    ]
