# Generated by Django 5.1.5 on 2025-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header Settings', 'verbose_name_plural': 'Header Settings'},
        ),
        migrations.AlterField(
            model_name='header',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='header',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='phone',
            field=models.CharField(default='+0123456789', help_text='Enter phone number in international format (+XXX...)', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='header',
            name='signup_url',
            field=models.URLField(default='/auth/login', verbose_name='Signup/Login URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
