# Generated by Django 5.1.5 on 2025-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_header_signup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='signup_url',
            field=models.URLField(default='/auth/login', verbose_name='Signup/Login URL'),
        ),
    ]
