# Generated by Django 5.1.5 on 2025-03-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_header_signup_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='signup_url',
            field=models.URLField(blank=True, default='/auth/login', help_text='Leave empty to hide signup link', null=True, verbose_name='Signup/Login URL'),
        ),
    ]
