# Generated by Django 5.1.5 on 2025-03-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_header_signup_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_title', models.CharField(max_length=100, verbose_name='Newsletter Title')),
                ('newsletter_description', models.TextField(verbose_name='Newsletter Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('map_link', models.URLField(blank=True, verbose_name='Map Link')),
                ('copyright_text', models.TextField(verbose_name='Copyright Text')),
                ('design_credit', models.TextField(verbose_name='Design Credit')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Link Title')),
                ('url', models.CharField(max_length=200, verbose_name='Link URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.footer')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
    ]
